### ISSUE TITLE
Add more blocks

### ISSUE THREAD

**Issue by kirstyellis** [shadow-robot/robot_blockly#10]
Add more blockly blocks, initially blocks that will be useful when creating demos next week (commencing the 25th Jan)
- Initialisation blocks; select hand/arm commander, right or left
- Create box for arm, similar to hand for moving to named positions
- Boxes for stages of trajectory generation, so, compute, plan and execute

**Comment by ugocupcic** [comment]
@kirstyellis better to split that one into one issue per box. This way it'll be easier to separate / prioritize / send pull request.
