### ISSUE TITLE
Add play / pause

### ISSUE THREAD

**Issue by ugocupcic** [shadow-robot/robot_blockly#15]

**Comment by ugocupcic** [comment]
Make sure you start this on the base branch so that we can send a pull request to erlerobotics!

**Comment by AndriyPt** [comment]
This is how it looks now 
![play_pause_demo](https://cloud.githubusercontent.com/assets/10820297/13044798/d8a5b1f0-d3d8-11e5-9c79-42b2c697a6d5.gif)

**Comment by ugocupcic** [comment]
awesome! Also shows #14
