### ISSUE TITLE
Blockly not working on Bravo

### ISSUE THREAD

**Issue by kirstyellis** [shadow-robot/robot_blockly#32]
On the Bravo laptop, blockly does not work. It launches without any errors. When a program is sent from the front end via the 'launch' button, in the backend the logs get to the point of building the node and then nothing else happens. This has not happened on any other machines, we re-installed blockly but the issue remained.

**Comment by ugocupcic** [comment]
Use docker 😉

On Tuesday, 3 May 2016, kirstyellis notifications@github.com wrote:

> On the Bravo laptop, blockly does not work. It launches without any
> errors. When a program is sent from the front end via the 'launch' button,
> in the backend the logs get to the point of building the node and then
> nothing else happens. This has not happened on any other machines, we
> re-installed blockly but the issue remained.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/shadow-robot/robot_blockly/issues/32

## 

Ugo Cupcic_Chief Technical Architect_+44 20 7700 2487

## 

---

_Shadow Robot Company Ltd._
251 Liverpool Road, N1 1LX, UK

## Registered Number 3308007 (England & Wales)

**Comment by kirstyellis** [comment]
re-installed ubuntu, now it works
